### ISSUE TITLE
Orleans.Streams.Utils project does not exist

### ISSUE THREAD

**Issue by jaypetrin** [jonathansant/Orleans.Streams.Kafka#12]
I cloned the repo so that I could implement the new version of Confluent. However, The project does not build in its current state. There seems to be a project that is missing from the repo called Orleans.Streams.Utils. There are references to the namespace in many classes as well as a Type that I believe would be included there as well, QueueProperties.

**Comment by jonathansant** [comment]
Hi, you'll need to clone this https://github.com/jonathansant/Orleans.Streams.Utils side by side to work in development.

**Comment by jaypetrin** [comment]
Awesome, thanks Jonathan.
