### ISSUE TITLE
Producer timeout by 'message.timeout.ms'

### ISSUE THREAD

**Issue by mkjeff** [jonathansant/Orleans.Streams.Kafka#2]
Just wondering, is it doable that control the producer's timeout by ['message.timeout.ms'](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) setting?

https://github.com/jonathansant/Orleans.Streams.Kafka/blob/94b287cb3db157c2558f3b5a1fd1afd93d8a896e/Orleans.Streams.Kafka/Producer/ProducerExtensions.cs#L13

**Comment by jonathansant** [comment]
Hi @mkjeff, sure thing I'll do some investigations with Confluent and get back to you. 

In the meantime, can you please clarify you prefer `message.timeout.ms` as opposed to `CancellationToken`?

**Comment by mkjeff** [comment]
Thank you for your quick response.  First of all, I think 'librdkafka' already provides a lower level of timeout control. With this setting, it can omit the overhead of the CancellationTokenSource object allocation. Secondly, from the 'librdkafka' document description, 'message.timeout.ms' has considered retry scenario. It seems more convenient for reliability control.

**Comment by jonathansant** [comment]
That's a fair point. Opened a PR: https://github.com/jonathansant/Orleans.Streams.Kafka/pull/3. I will merge it tomorrow if you have nothing to add.
