### ISSUE TITLE
Any interest in releasing as LGPL?

### ISSUE THREAD

**Issue by simplifymatt** [jonathansant/Orleans.Streams.Kafka#20]

**Comment by jonathansant** [comment]
Not much of a legal buff, care to specify some pros vs cons?

**Comment by simplifymatt** [comment]
Getting my details from here
https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)
The main point is anything linked to GPL v3 must also be GPL v3 (or compatible license) and made open source. IE I can't use this in any commercial project. Which if is the intent that's cool. Where as something like the LGPL v2 or MIT would allow it to be used in a commercial product without disclosing the source. 

https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)

There is also a LGPL v3 but it has an odd must disclose source for 3 years clause?!

**Comment by simplifymatt** [comment]
Def not a lawyer or expert but on more reading looks like as long as I don't distribute it and only keep it as a service then its fine. So closing this.
