### ISSUE TITLE
Possible issue with Confluent Cloud?

### ISSUE THREAD

**Issue by simplifymatt** [jonathansant/Orleans.Streams.Kafka#21]
Having a one message lag in confluent cloud for each partition, if I manually consume it via the example confluent app, it goes to 0, ie SystemStream. Any ideas?

![lag](https://user-images.githubusercontent.com/54920747/65006569-6c678980-d8d1-11e9-8e53-20d0befbfefd.PNG)

**Comment by jonathansant** [comment]
Hi, actually I found an issue with Confluent's consumer. Seems that the commit operation is failing. I'll investigate and keep you posted

**Comment by jonathansant** [comment]
Fixed using this [pr](https://github.com/jonathansant/Orleans.Streams.Kafka/pull/22) (use version: `3.0.0-dev-97`)
