### ISSUE TITLE
Question: One Topic with two consumer but different ConsumerGroupId? 

### ISSUE THREAD

**Issue by doctorcode-org** [jonathansant/Orleans.Streams.Kafka#33]
Hi
We need a topic subscribed by 2 consumers, but each consumer must be able to receive messages separately from the desired offset.
Do we need to define each group separately and redefine the topics for each group option?

**Comment by EugeneKrapivin** [comment]
you need to subscribe with 2 different consumer groups (and consequently, different consumers) to the same topic.
Kafka will treat each consumer group as a separate entity with separate offsets with regards to the topic

**Comment by doctorcode-org** [comment]
@EugeneKrapivin Thank you so much
This is my configuration:
```
.AddKafka("KafkaProvider")
.WithOptions(options =>
{
    options.BrokerList = new[] { "localhost:9092" };
    options.ConsumerGroupId = "TestGroup";
    options.AddTopic("rlc-test");
    options.AddTopic("sucrose-test");
})
.WithOptions(options =>
{
    options.BrokerList = new[] { "localhost:9092" };
    options.ConsumerGroupId = "TestGroup2";
    options.AddTopic("rlc-test");
    options.AddTopic("sucrose-test");
})
.AddLoggingTracker()
.Build();
```
Did I configure options correctly?

**Comment by EugeneKrapivin** [comment]
I think its should probably be something akin to
```csharp
.AddKafka("KafkaStream1")
	.WithOptions(options =>
	{
		options.BrokerList = new[] { "localhost:9092" };
		options.ConsumerGroupId = "TestGroup";
		options.AddTopic("rlc-test");
		options.AddTopic("sucrose-test");
	})
	.AddLoggingTracker()
	.Build();
.AddKafka("KafkaStream2")
	.WithOptions(options =>
	{
		options.BrokerList = new[] { "localhost:9092" };
		options.ConsumerGroupId = "TestGroup2";
		options.AddTopic("rlc-test");
		options.AddTopic("sucrose-test");
	})
	.AddLoggingTracker()
	.Build();
```

but those are my guesses, you'll have to test this a bit.

The reasoning is that Orleans has no knowledge of the concept of Kafka consumer groups. Hence, if you want to make 2 separate streams in Orleans, you'll have to register 2 streams, creating 2 separate consumer groups in the process.
