### ISSUE TITLE
[Feature] Add support for kafka headers

### ISSUE THREAD

**Issue by serpargu** [jonathansant/Orleans.Streams.Kafka#39]
Hi,

Using this library we faced a scenario where we needed to use the Headers from the Kafka message. so we think it could be acceptable to pass the whole result from Kafka instead just the payload.

To avoid a breaking change we extended the `IExternalStreamDeserializer` to support both usages in the method signature.

**Comment by serpargu** [comment]
[Required Orleans.Streams.Utils PR](https://github.com/jonathansant/Orleans.Streams.Utils/pull/10)

Fixed #40

**Comment by gomete** [comment]
Hi @jonathansant, did you have the opportunity to check this out?

Thank you in advance!
