### ISSUE TITLE
`Consume` invocation wrapped with Task seems redundant

### ISSUE THREAD

**Issue by mkjeff** [jonathansant/Orleans.Streams.Kafka#4]
https://github.com/jonathansant/Orleans.Streams.Kafka/blob/fe94cb39df144779330fa764f7fdff63a3268e8f/Orleans.Streams.Kafka/Consumer/ConsumerExtensions.cs#L13

Is it really necessary?

**Comment by jonathansant** [comment]
https://github.com/jonathansant/Orleans.Streams.Kafka/pull/6
